name: Deploy to AWS
on:
  workflow_dispatch:
    
jobs:
  deploy_after_build:
    runs-on: "ubuntu-latest"
    steps:
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Fail immediately if any command fails
          set -e
          
          # Move to project directory
          cd /home/ubuntu
          
          echo "Pulling latest Docker images..."
          docker compose -f solang-pg-analytics-test.yml pull
          
          echo "Starting containers with updated images..."
          docker compose -f solang-pg-analytics-test.yml up -d
          
          echo "Cleaning up old unused Docker images..."
          docker image prune -f
          
          echo "Deployment finished successfully!"